/* Generated by tools/host/clips.c: the word clips. */
#pragma once
#include <stdint.h>

typedef struct {
    const char *name;
    uint32_t samples;
    const uint8_t *data;    /* samples / 2 bytes of IMA ADPCM */
} clip_t;

enum {
    CLIP_HELLO,
    CLIP_UH_OH,
    CLIP_WOW,
    CLIP_OH_NO,
    CLIP_OKAY,
    CLIP_BYE_BYE,
    CLIP_OOPSIE,
    CLIP_REALLY,
    CLIP_SERIOUSLY,
    CLIP_WHATEVER,
    CLIP_NO_WAY,
    CLIP_THANK_YOU,
    CLIP_HOORAY,
    CLIP_SORRY,
    CLIP_PEEKABOO,
    CLIP_BINGO,
    CLIP_WAKEY_WAKEY,
    CLIP_GOOD_NIGHT,
    CLIP_GOOD_MORNING,
    CLIP_OOH_LA_LA,
    CLIP_AHA,
    CLIP_COME_ON,
    CLIP_EXCUSE_ME,
    CLIP_HOW_RUDE,
    CLIP_YUMMY,
    CLIP_BRAVO,
    CLIP_HI_THERE,
    CLIP_OH_REALLY,
    CLIP_FUCK_YOU,
    CLIP_SHUT_UP,
    CLIP_YOU_IDIOT,
    CLIP_GO_AWAY,
    CLIP_BITE_ME,
    CLIP_NERD,
    CLIP_LOSER,
    CLIP_BORING,
    CLIP_OH_PLEASE,
    CLIP_DUMB_DUMB,
    CLIP_SILLY,
    CLIP_BUZZ_OFF,
    CLIP_GET_LOST,
    CLIP_NOPE,
    CLIP_MEH,
    CLIP_AS_IF,
    CLIP_NOT_MY_PROBLEM,
    CLIP_LEAVE_ME_ALONE,
    CLIP_NICE_TRY,
    CLIP_YOU_WISH,
    CLIP_TALK_TO_THE_HAND,
    CLIP_WHATEVER_HUMAN,
    CLIP_I_AM_WATCHING_YOU,
    CLIP_DO_NOT_TOUCH_ME,
    CLIP_FEED_ME,
    CLIP_I_AM_BORED,
    CLIP_COUNT
};
extern const clip_t k_clips[CLIP_COUNT];
extern const int k_clips_n;
