import assert from 'node:assert/strict';
import fs from 'node:fs';
import {parseLine,decode,pack,unpack} from './trace.mjs';
import {timeline,wav,pcmStats,annotation,evaluate,intervals} from './replay.mjs';
const [p]=parseLine(fs.readFileSync('tools/host/out/trace-v3-fixture.log','utf8'));
assert.equal(p.length,1092);assert(decode(p).hasAudio);
const fixture=(seq,flags)=>{const q=p.slice(),v=new DataView(q.buffer);v.setUint32(0,seq*16,true);v.setUint32(24,seq,true);q[18]=flags;return q;};
const records=[fixture(0,64),fixture(1,64),fixture(4,0)],map=timeline(records);
assert.equal(map.duration,.08);assert.equal(map.gaps.length,1);assert.deepEqual(map.gaps[0],{start:.032,end:.064,reason:'Missing USB frames'});
const w=wav(records),v=new DataView(w.buffer);assert.equal(v.getUint16(22,true),2);assert.equal(v.getUint32(24,true),16000);
assert.equal(v.getInt16(44,true),2345);assert.equal(v.getInt16(46,true),-1234);assert.equal(v.getInt16(44+512*4,true),0);assert.equal(v.getInt16(44+1024*4,true),2345);
const stats=pcmStats(records);assert.equal(stats.samples,768);assert.deepEqual(stats.peak,[2345,1234]);assert.deepEqual(stats.rms,[2345,1234]);
assert.equal(new DataView(wav(records,{channel:'right'}).buffer).getInt16(44,true),-1234);
assert.deepEqual(intervals(map),[{start:0,end:.032}]);
const labels=[annotation(0,.08,'dance','needs music',map.duration)];let e=evaluate(map,labels);assert(Math.abs(e.tp-.032)<1e-9);assert(Math.abs(e.fn-.016)<1e-9);assert(Math.abs(e.labelled-.048)<1e-9);
labels.push(annotation(.016,.024,'no_dance','speech',map.duration));e=evaluate(map,labels);assert(Math.abs(e.conflict-.008)<1e-9);
assert.throws(()=>annotation(0,.2,'dance','',map.duration));assert.throws(()=>annotation(.03,.01,'dance','',map.duration));
const legacy=p.slice(0,64);assert(!decode(legacy).hasAudio);assert.throws(()=>wav([legacy]));
const round=unpack(await pack({tracks:[{annotations:labels}]},[legacy,...records]).arrayBuffer());assert.equal(round.meta.format,3);assert(!decode(round.records[0]).hasAudio);assert(decode(round.records[1]).hasAudio);assert.deepEqual(round.meta.tracks[0].annotations,labels);
assert.throws(()=>parseLine(fs.readFileSync('tools/host/out/trace-v3-fixture.log','utf8').replace('50434d31','50434d30')));
console.log('PASS: C stereo fixture, bit-exact L/R WAV, silent sequence gaps, channel audition, mixed files, range labels and overlap-safe scoring');

// Content and movement are independent; old labels stay unspecified.
const gentle=annotation(0,.016,'dance','',map.duration,{danceStyle:'slow',audibleContent:'speech_music'});
const singing=annotation(.016,.032,'dance','',map.duration,{danceStyle:'energetic',audibleContent:'music'});
const speech=annotation(.064,.08,'no_dance','',map.duration,{danceStyle:'none',audibleContent:'speech'});
const contentOnly=annotation(0,.016,'unsure','',map.duration,{audibleContent:'music'});
assert(!('danceStyle' in labels[0]));assert(!('danceStyle' in contentOnly));
assert.throws(()=>annotation(0,.016,'dance','',map.duration,{danceStyle:'none'}));
assert.throws(()=>annotation(0,.016,'no_dance','',map.duration,{danceStyle:'slow'}));
assert.throws(()=>annotation(0,.016,'dance','',map.duration,{danceStyle:'fastest'}));
assert.throws(()=>annotation(0,.016,'dance','',map.duration,{audibleContent:'singing_probably'}));
assert.throws(()=>annotation(0,.016,'unsure','',map.duration));
const newLabels=[gentle,singing,speech,contentOnly,labels[0]];
const enriched=unpack(await pack({tracks:[{annotations:newLabels}]},records).arrayBuffer());
assert.deepEqual(enriched.meta.tracks[0].annotations,newLabels);
assert.deepEqual(evaluate(map,newLabels),evaluate(map,newLabels.map(({danceStyle,audibleContent,...l})=>l)));
assert.equal(evaluate(map,[contentOnly]).labelled,0);
console.log('PASS: independent content/movement labels, legacy preservation, invalid combinations, notebook round trip and unchanged detection scoring');
