/* Sparse, exact four-sub-row charging rim coverage, generated once on the host. */
#include <stdint.h>
#include <stdio.h>
static uint32_t root(uint32_t n){uint32_t r=0,b=1u<<30;while(b>n)b>>=2;while(b){if(n>=r+b){n-=r+b;r=(r>>1)+b;}else r>>=1;b>>=2;}return r;}
static int chord(int r,int d){int64_t q=(int64_t)r*r-(int64_t)d*d;return q<=0?-1:(int)root(q);}
static uint16_t offset[467],xs[20000];static uint8_t coverage[20000];
int main(void){
 unsigned n=0;
 for(int y=0;y<466;y++){
  offset[y]=n;
  for(int x=0;x<466;x++){
   unsigned cov=0;
   for(int k=0;k<4;k++){
    int d=y*256+32+64*k-233*256,so=chord(232*256,d),si=chord(228*256,d);
    if(so<0)continue;
    int spans[2][2]={{233*256-so,233*256+(si<0?so:-si)},{233*256+si,233*256+so}};
    for(int j=0;j<(si<0?1:2);j++){
     int l=spans[j][0]>x*256?spans[j][0]:x*256,r=spans[j][1]<(x+1)*256?spans[j][1]:(x+1)*256;
     if(r>l)cov+=(r-l)*(k==3?63:64)>>8;
    }
   }
   if(cov){if(n>=20000)return 2;xs[n]=x;coverage[n++]=cov;}
  }
 }
 offset[466]=n;
 FILE *f=fopen("main/charge_coverage.h","w");if(!f)return 1;
 fputs("/* Generated by tools/host/charge_cache.c; exact sparse charging-ring coverage. */\n#pragma once\nstatic const uint16_t charge_row[467]={\n",f);
 for(int i=0;i<467;i++)fprintf(f,"%u,%s",offset[i],i%16==15?"\n":"");
 fprintf(f,"\n};\nstatic const uint16_t charge_x[%u]={\n",n);
 for(unsigned i=0;i<n;i++)fprintf(f,"%u,%s",xs[i],i%16==15?"\n":"");
 fprintf(f,"\n};\nstatic const uint8_t charge_cov[%u]={\n",n);
 for(unsigned i=0;i<n;i++)fprintf(f,"%u,%s",coverage[i],i%32==31?"\n":"");
 fputs("\n};\n",f);fprintf(stderr,"charge coverage: %u pixels, %u bytes flash\n",n,934+3*n);return fclose(f)!=0;
}
