/* Encode the processed word clips to IMA ADPCM C tables: clips <dir with list.txt and NN_*.wav> -> main/clips_gen.c/.h.
 * Leading and trailing silence below -50 dBFS is trimmed. Also writes a decoded round-trip medley for a listen. */
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "adpcm.h"

#define FS 16000

static int16_t *wav_read(const char *path, int *n)
{
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); exit(1); }
    uint8_t h[12];
    if (fread(h, 1, 12, f) != 12 || memcmp(h, "RIFF", 4)) { fprintf(stderr, "%s: not a WAV\n", path); exit(1); }
    int16_t *pcm = NULL;
    *n = 0;
    for (;;) {
        uint8_t ch[8];
        if (fread(ch, 1, 8, f) != 8) break;
        const uint32_t len = ch[4] | ch[5] << 8 | ch[6] << 16 | (uint32_t)ch[7] << 24;
        if (!memcmp(ch, "data", 4)) { pcm = malloc(len); *n = (int)(fread(pcm, 1, len, f) / 2); break; }
        fseek(f, (long)(len + (len & 1)), SEEK_CUR);
    }
    fclose(f);
    if (!pcm) { fprintf(stderr, "%s: no data\n", path); exit(1); }
    return pcm;
}

static void wav_write(const char *path, const int16_t *pcm, int n)
{
    FILE *f = fopen(path, "wb");
    if (!f) { perror(path); exit(1); }
    const uint32_t data = (uint32_t)n * 2, rate = FS, brate = rate * 2, fmtlen = 16, riff = 36 + data;
    const uint16_t ch = 1, bits = 16, align = 2, fmt = 1;
    fwrite("RIFF", 1, 4, f); fwrite(&riff, 4, 1, f); fwrite("WAVE", 1, 4, f);
    fwrite("fmt ", 1, 4, f); fwrite(&fmtlen, 4, 1, f); fwrite(&fmt, 2, 1, f); fwrite(&ch, 2, 1, f);
    fwrite(&rate, 4, 1, f); fwrite(&brate, 4, 1, f); fwrite(&align, 2, 1, f); fwrite(&bits, 2, 1, f);
    fwrite("data", 1, 4, f); fwrite(&data, 4, 1, f);
    fwrite(pcm, 2, (size_t)n, f);
    fclose(f);
}

static int16_t g_med[FS * 120];

int main(int argc, char **argv)
{
    if (argc < 2) { fprintf(stderr, "usage: clips <dir>\n"); return 1; }
    char path[512];
    snprintf(path, sizeof path, "%s/list.txt", argv[1]);
    FILE *lf = fopen(path, "r");
    if (!lf) { perror(path); return 1; }
    FILE *cf = fopen("../../main/clips_gen.c", "w"), *hf = fopen("../../main/clips_gen.h", "w");
    if (!cf || !hf) { perror("main/clips_gen"); return 1; }
    fprintf(cf, "/* Generated by tools/host/clips.c: the word clips, IMA ADPCM 16 kHz mono. Do not edit. */\n#include \"clips_gen.h\"\n\n");
    fprintf(hf, "/* Generated by tools/host/clips.c: the word clips. */\n#pragma once\n#include <stdint.h>\n\ntypedef struct {\n    const char *name;\n    uint32_t samples;\n    const uint8_t *data;    /* samples / 2 bytes of IMA ADPCM */\n} clip_t;\n\nenum {\n");
    char line[128];
    int count = 0, m = 0;
    size_t total = 0;
    char names[128][64];
    int lens[128];
    while (fgets(line, sizeof line, lf) && count < 128) {
        int idx;
        char name[96];
        if (sscanf(line, "%d %[^\n]", &idx, name) != 2) continue;
        char slug[96];
        int k = 0;
        for (const char *c = name; *c && k < 60; c++) {
            const int ok = (*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9');
            if (ok) slug[k++] = *c;
            else if (k && slug[k - 1] != '_') slug[k++] = '_';
        }
        while (k && slug[k - 1] == '_') k--;
        slug[k] = 0;
        snprintf(path, sizeof path, "%s/%02d_%s.wav", argv[1], idx, slug);
        int n;
        int16_t *pcm = wav_read(path, &n);
        /* trim */
        const int thr = (int)(32767 * pow(10.0, -50.0 / 20.0));
        int a = 0, b = n;
        while (a < n && abs(pcm[a]) < thr) a++;
        while (b > a && abs(pcm[b - 1]) < thr) b--;
        a = a > 80 ? a - 80 : 0;
        b = b + 160 < n ? b + 160 : n;
        int len = b - a;
        if (len & 1) len--;
        adpcm_state_t st = { 0, 0 };
        uint8_t *enc = malloc((size_t)len / 2);
        adpcm_encode(&st, pcm + a, enc, len);
        fprintf(cf, "static const uint8_t c_%s[%d] = {", slug, len / 2);
        for (int i = 0; i < len / 2; i++) fprintf(cf, "%s%u", i == 0 ? "\n    " : i % 24 ? "," : ",\n    ", enc[i]);
        fprintf(cf, "\n};\n");
        char up[96];
        for (k = 0; slug[k]; k++) up[k] = (slug[k] >= 'a' && slug[k] <= 'z') ? slug[k] - 32 : slug[k];
        up[k] = 0;
        fprintf(hf, "    CLIP_%s,\n", up);
        snprintf(names[count], sizeof names[count], "%s", name);
        lens[count] = len;
        total += (size_t)len / 2;
        /* round trip into the medley */
        adpcm_state_t ds = { 0, 0 };
        adpcm_decode(&ds, enc, g_med + m, len);
        m += len + FS * 4 / 10;
        free(enc);
        free(pcm);
        count++;
    }
    fclose(lf);
    fprintf(cf, "\nconst clip_t k_clips[%d] = {\n", count);
    for (int i = 0; i < count; i++) {
        char slug[96];
        int k = 0;
        for (const char *c = names[i]; *c && k < 60; c++) {
            const int ok = (*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9');
            if (ok) slug[k++] = *c;
            else if (k && slug[k - 1] != '_') slug[k++] = '_';
        }
        while (k && slug[k - 1] == '_') k--;
        slug[k] = 0;
        fprintf(cf, "    { \"%s\", %d, c_%s },\n", names[i], lens[i], slug);
    }
    fprintf(cf, "};\nconst int k_clips_n = %d;\n", count);
    fprintf(hf, "    CLIP_COUNT\n};\nextern const clip_t k_clips[CLIP_COUNT];\nextern const int k_clips_n;\n");
    fclose(cf);
    fclose(hf);
    wav_write("../../docs/voice/clips_roundtrip.wav", g_med, m);
    printf("%d clips, %zu bytes of ADPCM -> main/clips_gen.c; docs/voice/clips_roundtrip.wav\n", count, total);
    return 0;
}
