#!/usr/bin/env python3
"""Convert a monospace BDF font into a C glyph table for gfx.c.

usage: bdf2c.py FONT.bdf NAME OUT.c
Glyphs: ASCII 0x20..0x7E first (direct index), then a sorted list of extra
codepoints (box drawing, arrows, bullets) looked up by binary search.
Rows are stored MSB-first, (cell_width + 7) / 8 bytes per row.
"""
import sys, re

EXTRAS = [0x00B0, 0x00B7, 0x2022, 0x2190, 0x2191, 0x2192, 0x2193, 0x2195,
          0x2500, 0x2502, 0x250C, 0x2510, 0x2514, 0x2518, 0x251C, 0x2524,
          0x252C, 0x2534, 0x253C, 0x2550, 0x2551, 0x2588, 0x2591, 0x2592,
          0x25A0, 0x25B2, 0x25BC, 0x25C0, 0x25B6, 0x25CB, 0x25CF, 0x2713, 0x2717]

def parse(path):
    glyphs = {}
    cell_w = cell_h = asc = desc = None
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().splitlines()
    i = 0
    while i < len(lines):
        l = lines[i]
        if l.startswith("FONTBOUNDINGBOX"):
            _, w, h, _, _ = l.split(); cell_w, cell_h = int(w), int(h)
        elif l.startswith("FONT_ASCENT"):
            asc = int(l.split()[1])
        elif l.startswith("FONT_DESCENT"):
            desc = int(l.split()[1])
        elif l.startswith("STARTCHAR"):
            enc = None; bbx = None; rows = []
            i += 1
            while not lines[i].startswith("ENDCHAR"):
                t = lines[i]
                if t.startswith("ENCODING"):
                    enc = int(t.split()[1])
                elif t.startswith("BBX"):
                    bbx = tuple(int(v) for v in t.split()[1:5])
                elif t.startswith("BITMAP"):
                    i += 1
                    while not lines[i].startswith("ENDCHAR"):
                        rows.append(lines[i].strip()); i += 1
                    continue
                i += 1
            if enc is not None and enc >= 0:
                glyphs[enc] = (bbx, rows)
        i += 1
    return cell_w, cell_h, asc, desc, glyphs

def render(cell_w, cell_h, asc, bbx, rows):
    """Place a glyph bitmap into the full cell; returns cell_h ints of cell_w bits."""
    bw, bh, bx, by = bbx
    cell = [0] * cell_h
    top = asc - (by + bh)              # cell row of the glyph's top row
    src_bytes = (bw + 7) // 8
    for r, hexrow in enumerate(rows[:bh]):
        bits = int(hexrow, 16) >> (src_bytes * 8 - bw)   # left-aligned bw bits
        y = top + r
        if 0 <= y < cell_h:
            shifted = bits << (cell_w - bw - bx) if (cell_w - bw - bx) >= 0 else bits >> -(cell_w - bw - bx)
            cell[y] |= shifted & ((1 << cell_w) - 1)
    return cell

def main():
    src, name, out = sys.argv[1:4]
    cell_w, cell_h, asc, desc, glyphs = parse(src)
    bpr = (cell_w + 7) // 8
    cps = list(range(0x20, 0x7F)) + [c for c in EXTRAS if c in glyphs]
    extras = [c for c in EXTRAS if c in glyphs]
    lines = []
    lines.append("/* Generated by tools/bdf2c.py from %s. Do not edit.\n *\n" % src.split('/')[-1])
    lines.append(" * Spleen is Copyright (c) 2018-2026, Frederic Cambus, BSD 2-Clause License:\n")
    lines.append(" * Redistribution and use in source and binary forms, with or without modification,\n"
                 " * are permitted provided that the copyright notice, the conditions and the\n"
                 " * disclaimer of the BSD 2-Clause License are retained (see tools/bdf2c.py and\n"
                 " * https://github.com/fcambus/spleen/blob/master/LICENSE).\n */\n")
    lines.append('#include "gfx.h"\n\n')
    lines.append("static const uint8_t %s_bitmap[%d * %d * %d] = {\n" % (name, len(cps), cell_h, bpr))
    for cp in cps:
        bbx, rows = glyphs.get(cp, glyphs[0x20] if 0x20 in glyphs else ((cell_w, cell_h, 0, -desc), ["0" * (bpr * 2)] * cell_h))
        cell = render(cell_w, cell_h, asc, bbx, rows)
        byts = []
        for v in cell:
            v <<= (bpr * 8 - cell_w)          # MSB-first, left aligned in the row bytes
            for b in range(bpr):
                byts.append((v >> (8 * (bpr - 1 - b))) & 0xFF)
        label = chr(cp) if 0x20 <= cp < 0x7F and cp != 0x5C and cp != 0x2A else "U+%04X" % cp
        lines.append("    /* %s */ %s,\n" % (label, ", ".join("0x%02X" % b for b in byts)))
    lines.append("};\n\n")
    lines.append("static const uint16_t %s_extras[%d] = { %s };\n\n" % (name, max(1, len(extras)), ", ".join("0x%04X" % c for c in extras) or "0"))
    lines.append("const gfx_font_t %s = {\n    .w = %d, .h = %d, .bytes_per_row = %d, .ascent = %d,\n"
                 "    .bitmap = %s_bitmap,\n    .extras = %s_extras,\n    .n_extras = %d,\n};\n"
                 % (name, cell_w, cell_h, bpr, asc, name, name, len(extras)))
    open(out, "w").write("".join(lines))
    print("%s: %d glyphs (%d extras), %d bytes" % (name, len(cps), len(extras), len(cps) * cell_h * bpr))

if __name__ == "__main__":
    main()
